### ISSUE TITLE
Forum: model

### ISSUE THREAD

**Issue by ajrouvoet** [csrdelft/balins-adventure#11]

**Comment by ajrouvoet** [comment]
Afaik this is :+1: in master

**Comment by thervh70** [comment]
Models.py is supposed to have a get_viewable_by() method, especially in the forum this is important. Only after this has been implemented #15 can be fixed

**Comment by ajrouvoet** [comment]
Not every model necessarily has a `get_viewable_by`. Moreover, forum posts do NOT have permissions associated with them directly. This is handled by the ForumDeel that they belong to. And this one already has a `get_viewable_by` (the original one, namely ;-)

**Comment by brussee** [comment]
Dit is nog een interessante, want 'goedgekeurd' is een soort permission check: zichtbaar voor alleen moderatoren totdat de externe post is goedgekeurd, daarna zichtbaar for all.
