### ISSUE TITLE
Forum views

### ISSUE THREAD

**Issue by ajrouvoet** [csrdelft/balins-adventure#14]
- [x] list draden view
- [x] n most recent view
- [x] forum deel dropdown (possibly using (this)[http://material-ui.com/#/components/dropdown-menu])
- [ ] create forum draad (possibly with reusable generic form view using material-ui form thingies)
- [ ]

**Comment by ajrouvoet** [comment]
Would be good if we can find a generic React tables package on npm and use this to render the tables within the client.

**Comment by ajrouvoet** [comment]
Most of this is merged, I'll make a new ticket for the forms.

**Comment by brussee** [comment]
Think about the breadcrumbs: the ForumDeel backlink from a thread brings you back to the right _page_.
