### ISSUE TITLE
Generic form UI based for post endoints

### ISSUE THREAD

**Issue by ajrouvoet** [csrdelft/balins-adventure#16]
Either by specifying the fields + types and generating a form in React (using react-material ui form inputs!) or by getting the form fields dynamically..
Rest framework supplies an OPTIONS route that might be helpful for this case

**Comment by brussee** [comment]
Also remember fancy form fields like Dropzone.

**Comment by ajrouvoet** [comment]
This is in master now, working on Form posting & server side validation (client side validation works)

**Comment by ajrouvoet** [comment]
Continued work in the forum-posting branch

**Comment by ajrouvoet** [comment]
This is now merged, see forum module for examples of usage
