### ISSUE TITLE
OPTIONS on endpoints may leak data

### ISSUE THREAD

**Issue by ajrouvoet** [csrdelft/balins-adventure#59]
OPTIONS request on most resources are public, but they can leak data through available options.
This should be fixed.

**Comment by thervh70** [comment]
Op welke apps / services heeft dit invloed?

**Comment by ajrouvoet** [comment]
Alle ViewSets supporten automatisch OPTIONS requests. Dat is fijn, maar dan moeten we die ofwel intern maken, ofwel de available options die automatisch op sommige fields worden teruggegeven weghalen.

Voor het intern maken van die metadata kunnen we vast wel een mixin maken.

**Comment by ajrouvoet** [comment]
When using the `StekViewSet` as a viewset base class, the metadata is overridden to be very minimal; this solves this issue.
