### ISSUE TITLE
Possible bugs found during testing

### ISSUE THREAD

**Issue by thervh70** [csrdelft/balins-adventure#61]
- [x] `ProfielMiddleware` never authenticates a request.user
- [x] `Mededeling.get_viewable_by` requires `profiel.user.is_authenticated()` in order to work (so a profiel has a user?? ithought it was reversed) It gets passed the `request.user` by `ViewSet.get_queryset`
- [x] Current DB doesn't contain `x999`, it is mentioned in the code (`ProfielMiddleware`)

**Comment by thervh70** [comment]
Build fails because of the non-authenticated tests (they passed locally)

**Comment by ajrouvoet** [comment]
I think we fixed all of them now, let's see if the build passes once I get redis disabled in testing.
