### ISSUE TITLE
Announcement API test

### ISSUE THREAD

**Issue by ajrouvoet** [csrdelft/balins-adventure#9]
Ja dat dus. Ieg zorgen dat alle permissions getest worden. public/private/different levels

**Comment by thervh70** [comment]
## Post / Delete
- [x] Bestuur
- [x] Leden
- [x] Superuser

## Get
- [x] Leden
- [x] Oudleden
- [x] Externen (niet ingelogd)

**Comment by brussee** [comment]
Komt er weer een Queue for approval?

**Comment by ajrouvoet** [comment]
Denk het niet. Mededelingen wordt nu zo weinig gebruikt dat we het even hebben versimpeld.
